title: Hoy Transnoche Log
author:
  name: franaln
  email: franal@gmail.com

description: >
  Todos los episodios del unico podcast del mundo con las peliculas de las que
  hablan en cada uno + algunos graficos con estadisticas + ...

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - episodes.md
  - stats.md

header_pages:
  - episodes.md
  - stats.md

theme: minima
