title: Hoy Transnoche Log

author:
  name: "franaln"
  email: "franal@gmail.com"

description: >
  Todos los episodios del unico podcast del mundo con las peliculas de las que
  hablan en cada uno + algunos graficos con estadisticas + ...

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

relative_links:
  enabled: true
  collections: true

include:
  - episodes.md
  - stats.md

header_pages:
  - episodes.md
  - stats.md

theme: minima

minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/franaln/hoy-trasnoche-log" }
    - { platform: instagram,      user_url: "https://www.instagram.com/filmejuntoalpueblo" }