title: Hoy Transnoche Log

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - episodes.md
  - stats.md

header_pages:
  - episodes.md
  - stats.md

theme: minima
